import { Coffee, Utensils, Cake, Wine, ChefHat } from "lucide-react"
import type { Category, MenuItem } from "./types"

export const categories: Category[] = [
  { id: "breakfast", name: "Səhər Yeməyi", icon: Coffee },
  { id: "soups", name: "Şorbalar", icon: Utensils },
  { id: "salads", name: "Salatlar", icon: Utensils },
  { id: "appetizers", name: "İsti Qəlyanaltılar", icon: Utensils },
  { id: "cold-appetizers", name: "Soyuq Qəlyanaltılar", icon: Utensils },
  { id: "mains", name: "Əsas Yeməklər", icon: ChefHat },
  { id: "seafood", name: "Dəniz Məhsulları", icon: Utensils },
  { id: "pizza-pasta", name: "Pizza & Pasta", icon: Utensils },
  { id: "desserts", name: "Şirniyyatlar", icon: Cake },
  { id: "drinks", name: "İçkilər", icon: Coffee },
  { id: "alcohol", name: "Alkoqollu İçkilər", icon: Wine },
]

export const menuItems: Record<string, MenuItem[]> = {
  breakfast: [
    {
      id: 101,
      name: "Klassik Omlet",
      description: "3 yumurtadan hazırlanmış omlet",
      detailedDescription:
        "Təzə yumurtalardan hazırlanmış klassik omlet, kərə yağı ilə qızardılır. İstəyə görə pendir və tərəvəzlər əlavə edilə bilər.",
      ingredients: ["Yumurta", "Süd", "Kərə yağı", "Duz", "İstiot"],
      price: 8.0,
      image: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?w=400&h=300&fit=crop&auto=format",
      options: {
        extras: ["Pendir", "Göyərti", "Pomidor", "Soğan"],
      },
    },
    {
      id: 102,
      name: "Pancake",
      description: "Bal və meyvə ilə",
      detailedDescription: "Yumşaq və dadlı pancake-lər, təzə bal və mövsümi meyvələrlə təqdim olunur.",
      ingredients: ["Un", "Yumurta", "Süd", "Şəkər", "Baking powder", "Bal", "Meyvə"],
      price: 10.0,
      image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&h=300&fit=crop&auto=format",
      options: {
        extras: ["Əlavə Bal", "Dondurma", "Çikolat Sousu"],
      },
    },
    {
      id: 103,
      name: "Menemen",
      description: "Yumurta və tərəvəzlə",
      detailedDescription: "Türk mətbəxinin məşhur səhər yeməyi. Pomidor, bibər və yumurta ilə hazırlanır.",
      ingredients: ["Yumurta", "Pomidor", "Yaşıl bibər", "Soğan", "Zeytun yağı", "Ədviyyat"],
      price: 9.0,
      image: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=400&h=300&fit=crop&auto=format",
    },
    {
      id: 104,
      name: "Avokado Toast",
      description: "Təzə avokado ilə",
      detailedDescription: "Qızardılmış çörək üzərinə əzilmiş avokado, limon və ədviyyatlarla.",
      ingredients: ["Çörək", "Avokado", "Limon", "Zeytun yağı", "Duz", "İstiot"],
      price: 12.0,
      image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400&h=300&fit=crop&auto=format",
      options: {
        extras: ["Yumurta", "Pomidor", "Feta Pendir"],
      },
    },
  ],
  soups: [
    {
      id: 201,
      name: "Mercimek Şorbası",
      description: "Qırmızı mercimək şorbası",
      detailedDescription:
        "Türk mətbəxinin ən sevimli şorbalarından biri. Qırmızı mercimək və tərəvəzlərlə hazırlanır.",
      ingredients: ["Qırmızı mercimək", "Soğan", "Havuç", "Kartof", "Pomidor pastası", "Ədviyyat"],
      price: 6.0,
      image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop&auto=format",
    },
    {
      id: 202,
      name: "Toyuq Şorbası",
      description: "Ev şəraitində hazırlanmış",
      detailedDescription: "Təzə toyuq əti və tərəvəzlərlə uzun müddət qaynadılmış şorba.",
      ingredients: ["Toyuq əti", "Havuç", "Kartof", "Soğan", "Şəhəriyyə", "Göyərti"],
      price: 8.0,
      image: "https://images.unsplash.com/photo-1562967914-608f82629710?w=400&h=300&fit=crop&auto=format",
    },
    {
      id: 203,
      name: "Düyü Şorbası",
      description: "Kremli düyü şorbası",
      detailedDescription: "Kremli teksturaya malik düyü şorbası, tərəvəzlər və ədviyyatlarla zənginləşdirilir.",
      ingredients: ["Düyü", "Süd", "Kərə yağı", "Soğan", "Havuç", "Ədviyyat"],
      price: 7.0,
      image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=400&h=300&fit=crop&auto=format",
    },
  ],
  salads: [
    {
      id: 301,
      name: "Sezar Salatı",
      description: "Klassik Sezar sousu ilə",
      detailedDescription: "Xırtıldayan kahı, parmesan pendiri və xüsusi Sezar sousu ilə hazırlanmış klassik salat.",
      ingredients: ["Kahı", "Parmesan", "Kruton", "Sezar sousu", "Sarımsaq"],
      price: 14.0,
      image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400&h=300&fit=crop&auto=format",
      options: {
        extras: ["Toyuq əti", "Krevetka", "Avokado"],
      },
    },
    {
      id: 302,
      name: "Yunan Salatı",
      description: "Feta pendiri və zeytunla",
      detailedDescription: "Təzə tərəvəzlər, feta pendiri və zeytunlarla hazırlanmış Aralıq dənizi salatı.",
      ingredients: ["Pomidor", "Xiyar", "Soğan", "Feta pendiri", "Zeytun", "Zeytun yağı"],
      price: 12.0,
      image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=300&fit=crop&auto=format",
    },
    {
      id: 303,
      name: "Çoban Salatı",
      description: "Ənənəvi Türk salatı",
      detailedDescription: "Təzə doğranmış tərəvəzlərlə hazırlanmış ənənəvi salat.",
      ingredients: ["Pomidor", "Xiyar", "Soğan", "Göyərti", "Limon", "Zeytun yağı"],
      price: 8.0,
      image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop&auto=format",
    },
    {
      id: 304,
      name: "Roka Salatı",
      description: "Parmesan və qozla",
      detailedDescription: "Təzə roka yarpaqları, parmesan pendiri və qozlarla hazırlanmış salat.",
      ingredients: ["Roka", "Parmesan", "Qoz", "Balzamik sirka", "Zeytun yağı"],
      price: 13.0,
      image: "https://images.unsplash.com/photo-1505576391880-b3f9d713dc4f?w=400&h=300&fit=crop&auto=format",
    },
  ],
  appetizers: [
    {
      id: 1,
      name: "Qızardılmış Pendirli Çörək",
      description: "Xüsusi pendirli və otlu çörək",
      detailedDescription:
        "Təzə hazırlanmış çörək üzərinə xüsusi pendir qarışığı və ətirli otlar əlavə edilərək qızardılır.",
      ingredients: ["Ağ çörək", "Mozzarella", "Cheddar", "Reyhan", "Oregano", "Sarımsaq"],
      price: 8.5,
      image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=300&fit=crop&auto=format",
      options: {
        spicyLevel: ["Acısız", "Az Acı", "Orta Acı", "Çox Acı"],
        extras: ["Əlavə Pendir", "Zeytun", "Pomidor"],
      },
    },
    {
      id: 2,
      name: "Sigara Böreği",
      description: "Pendirli sigara böreği",
      detailedDescription: "Nazik yufka içərisində pendir qarışığı, qızardılmış və xırtıldayan.",
      ingredients: ["Yufka", "Beyaz pendir", "Göyərti", "Yumurta", "Zeytun yağı"],
      price: 10.0,
      image: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=400&h=300&fit=crop&auto=format",
    },
    {
      id: 3,
      name: "Dolma",
      description: "Ənənəvi Azərbaycan dolması",
      detailedDescription: "Nənəmizin resepti ilə hazırlanmış ənənəvi dolma. Təzə üzüm yarpağına sarılmış ətli dolma.",
      ingredients: ["Üzüm yarpağı", "Qoyun əti", "Düyü", "Soğan", "Göyərti", "Ədviyyat"],
      price: 10.0,
      image: "https://images.unsplash.com/photo-1574484284002-952d92456975?w=400&h=300&fit=crop&auto=format",
      options: {
        spicyLevel: ["Acısız", "Az Acı", "Orta Acı"],
        extras: ["Qatıq", "Sarımsaq Sousu"],
      },
    },
    {
      id: 4,
      name: "Mantar Sote",
      description: "Kərə yağında qızardılmış",
      detailedDescription: "Təzə mantarlar kərə yağında qızardılır, sarımsaq və otlarla dadlandırılır.",
      ingredients: ["Mantar", "Kərə yağı", "Sarımsaq", "Göyərti", "Ədviyyat"],
      price: 9.0,
      image: "https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=400&h=300&fit=crop&auto=format",
    },
  ],
  "cold-appetizers": [
    {
      id: 401,
      name: "Badımcan Ikrası",
      description: "Ev şəraitində hazırlanmış",
      detailedDescription: "Odda qızardılmış badımcanlardan hazırlanmış kremalı ikra.",
      ingredients: ["Badımcan", "Pomidor", "Soğan", "Sarımsaq", "Zeytun yağı"],
      price: 7.5,
      image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=300&fit=crop&auto=format",
    },
    {
      id: 402,
      name: "Humus",
      description: "Noxud pastası",
      detailedDescription: "Klassik Ərəb mətbəxindən humus, zeytun yağı və ədviyyatlarla.",
      ingredients: ["Noxud", "Tahin", "Limon", "Sarımsaq", "Zeytun yağı"],
      price: 8.0,
      image: "https://images.unsplash.com/photo-1571197119282-7c4a2b8a4b8b?w=400&h=300&fit=crop&auto=format",
    },
    {
      id: 403,
      name: "Cacık",
      description: "Xiyarlı qatıq",
      detailedDescription: "Təzə xiyar və qatıqdan hazırlanmış sərinləşdirici meze.",
      ingredients: ["Qatıq", "Xiyar", "Sarımsaq", "Nanə", "Zeytun yağı"],
      price: 6.0,
      image: "https://images.unsplash.com/photo-1563379091339-03246963d96c?w=400&h=300&fit=crop&auto=format",
    },
    {
      id: 404,
      name: "Zeytun Qarışığı",
      description: "Müxtəlif zeytun növləri",
      detailedDescription: "Qara və yaşıl zeytunların qarışığı, ədviyyatlar və zeytun yağı ilə marinə edilmiş.",
      ingredients: ["Qara zeytun", "Yaşıl zeytun", "Zeytun yağı", "Ədviyyat"],
      price: 9.0,
      image: "https://images.unsplash.com/photo-1452827073306-6e6e661baf57?w=400&h=300&fit=crop&auto=format",
    },
  ],
  mains: [
    {
      id: 5,
      name: "Plov",
      description: "Ənənəvi Azərbaycan plovu",
      detailedDescription:
        "Azərbaycan mətbəxinin ən məşhur yeməyi. Xüsusi düyü, qoyun əti və ədviyyatlarla hazırlanmış.",
      ingredients: ["Düyü", "Qoyun əti", "Soğan", "Kəsmik", "Şabalıd", "Zəfəran"],
      price: 18.0,
      image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=300&fit=crop&auto=format",
      options: {
        size: ["Kiçik", "Orta", "Böyük"],
        spicyLevel: ["Acısız", "Az Acı", "Orta Acı"],
        extras: ["Əlavə Ət", "Quru Meyvə", "Badım"],
      },
    },
    {
      id: 6,
      name: "Kəbab",
      description: "Mangalda bişirilmiş ət kəbabı",
      detailedDescription: "Seçilmiş qoyun ətindən hazırlanmış kəbab, mangalda xüsusi texnika ilə bişirilir.",
      ingredients: ["Qoyun əti", "Soğan", "Duz", "İstiot", "Sumaq", "Ədviyyat"],
      price: 22.0,
      image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop&auto=format",
      options: {
        spicyLevel: ["Acısız", "Az Acı", "Orta Acı", "Çox Acı"],
        extras: ["Çörək", "Soğan", "Sumaq"],
      },
    },
    {
      id: 7,
      name: "Toyuq Şnitsel",
      description: "Qızardılmış toyuq əti",
      detailedDescription: "Nazik döyülmüş toyuq əti, xüsusi galeta ilə örtülərək qızardılır.",
      ingredients: ["Toyuq əti", "Galeta", "Yumurta", "Un", "Zeytun yağı"],
      price: 16.0,
      image: "https://images.unsplash.com/photo-1562967914-608f82629710?w=400&h=300&fit=crop&auto=format",
      options: {
        size: ["Kiçik", "Orta", "Böyük"],
        extras: ["Kartof", "Salat", "Sous"],
      },
    },
    {
      id: 8,
      name: "Biftek",
      description: "Premium dana əti",
      detailedDescription: "Seçilmiş dana ətindən hazırlanmış biftek, istədiyiniz bişirmə dərəcəsində.",
      ingredients: ["Dana əti", "Kərə yağı", "Sarımsaq", "Reyhan", "Ədviyyat"],
      price: 35.0,
      image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop&auto=format",
      options: {
        spicyLevel: ["Rare", "Medium Rare", "Medium", "Well Done"],
        extras: ["Kartof", "Tərəvəz", "Sous"],
      },
    },
  ],
  seafood: [
    {
      id: 501,
      name: "Balıq Filesi",
      description: "Qızardılmış balıq filesi",
      detailedDescription: "Təzə dəniz balığından hazırlanmış file, xüsusi ədviyyatlarla marinə edilib qızardılır.",
      ingredients: ["Balıq filesi", "Limon", "Zeytun yağı", "Duz", "İstiot", "Reyhan"],
      price: 25.0,
      image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&h=300&fit=crop&auto=format",
      options: {
        extras: ["Limon", "Kartof", "Tərəvəz"],
      },
    },
    {
      id: 502,
      name: "Krevetka Sote",
      description: "Sarımsaklı krevetka",
      detailedDescription: "Təzə krevetkalar sarımsaq və kərə yağında sote edilir.",
      ingredients: ["Krevetka", "Sarımsaq", "Kərə yağı", "Ağ şərab", "Göyərti"],
      price: 28.0,
      image: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400&h=300&fit=crop&auto=format",
    },
    {
      id: 503,
      name: "Qızılbalıq Steyki",
      description: "Qril edilmiş qızılbalıq",
      detailedDescription: "Təzə qızılbalıq steyki, qrildə mükəmməl şəkildə bişirilir.",
      ingredients: ["Qızılbalıq", "Limon", "Zeytun yağı", "Ədviyyat"],
      price: 32.0,
      image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400&h=300&fit=crop&auto=format",
    },
    {
      id: 504,
      name: "Dəniz Məhsulları Qarışığı",
      description: "Müxtəlif dəniz məhsulları",
      detailedDescription: "Krevetka, midye və balıq qarışığı, xüsusi sous ilə hazırlanır.",
      ingredients: ["Krevetka", "Midye", "Balıq", "Soğan", "Pomidor", "Ağ şərab"],
      price: 30.0,
      image: "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=400&h=300&fit=crop&auto=format",
    },
  ],
  "pizza-pasta": [
    {
      id: 601,
      name: "Marqarita Pizza",
      description: "Klassik İtalyan pizzası",
      detailedDescription: "Pomidor sousu, mozzarella pendiri və təzə reyhan ilə hazırlanmış klassik pizza.",
      ingredients: ["Pizza xəmiri", "Pomidor sousu", "Mozzarella", "Reyhan", "Zeytun yağı"],
      price: 16.0,
      image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=300&fit=crop&auto=format",
      options: {
        size: ["Kiçik", "Orta", "Böyük"],
        extras: ["Əlavə Pendir", "Zeytun", "Mantar"],
      },
    },
    {
      id: 602,
      name: "Pepperoni Pizza",
      description: "Pepperoni ilə pizza",
      detailedDescription: "Klassik pepperoni pizza, mozzarella pendiri və xüsusi ədviyyatlarla.",
      ingredients: ["Pizza xəmiri", "Pomidor sousu", "Mozzarella", "Pepperoni"],
      price: 18.0,
      image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=300&fit=crop&auto=format",
      options: {
        size: ["Kiçik", "Orta", "Böyük"],
        spicyLevel: ["Acısız", "Az Acı", "Orta Acı"],
      },
    },
    {
      id: 603,
      name: "Spaghetti Bolognese",
      description: "Ət sousu ilə spagetti",
      detailedDescription: "Klassik İtalyan pastası, zəngin ət sousu və parmesan pendiri ilə.",
      ingredients: ["Spaghetti", "Dana əti", "Pomidor", "Soğan", "Havuç", "Parmesan"],
      price: 15.0,
      image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=400&h=300&fit=crop&auto=format",
    },
    {
      id: 604,
      name: "Fettuccine Alfredo",
      description: "Kremli sous ilə pasta",
      detailedDescription: "Fettuccine pastası kremli alfredo sousu və parmesan pendiri ilə.",
      ingredients: ["Fettuccine", "Qaymaq", "Parmesan", "Kərə yağı", "Sarımsaq"],
      price: 14.0,
      image: "https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=400&h=300&fit=crop&auto=format",
    },
  ],
  desserts: [
    {
      id: 9,
      name: "Baklava",
      description: "Ənənəvi Azərbaycan baklavası",
      detailedDescription: "Nazik xəmir təbəqələri arasına qoz və badam qarışığı qoyularaq hazırlanır.",
      ingredients: ["Xəmir", "Qoz", "Badam", "Bal", "Şəkər", "Kərə yağı"],
      price: 6.0,
      image: "https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=400&h=300&fit=crop&auto=format",
      options: {
        extras: ["Dondurma", "Bal", "Fıstıq"],
      },
    },
    {
      id: 10,
      name: "Tiramisu",
      description: "İtalyan şirniyyatı",
      detailedDescription: "Klassik İtalyan deserti. Qəhvə ilə isladılmış biskvit, maskarpone pendiri və kakao.",
      ingredients: ["Biskvit", "Qəhvə", "Maskarpone", "Yumurta", "Şəkər", "Kakao"],
      price: 8.0,
      image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit=crop&auto=format",
      options: {
        extras: ["Əlavə Kakao", "Çikolat Chip"],
      },
    },
    {
      id: 11,
      name: "Çikolat Tortu",
      description: "Ev şəraitində hazırlanmış",
      detailedDescription: "Zəngin çikolat dadı olan tort. Çikolat biskvit və çikolat kremindən ibarət.",
      ingredients: ["Çikolat", "Un", "Yumurta", "Şəkər", "Kərə yağı", "Süd"],
      price: 7.0,
      image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop&auto=format",
      options: {
        extras: ["Dondurma", "Meyvə", "Şokolad Sousu"],
      },
    },
    {
      id: 12,
      name: "Cheesecake",
      description: "New York üslubunda",
      detailedDescription: "Klassik New York cheesecake, meyvə sousu ilə təqdim olunur.",
      ingredients: ["Krem pendir", "Yumurta", "Şəkər", "Biskvit", "Kərə yağı"],
      price: 9.0,
      image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=400&h=300&fit=crop&auto=format",
      options: {
        extras: ["Çiyələk Sousu", "Böyürtkən Sousu", "Karamel"],
      },
    },
  ],
  drinks: [
    {
      id: 13,
      name: "Çay",
      description: "Azərbaycan çayı",
      detailedDescription: "Lankaran çayından hazırlanmış ənənəvi Azərbaycan çayı.",
      ingredients: ["Qara çay", "Su"],
      price: 3.0,
      image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&h=300&fit=crop&auto=format",
      options: {
        extras: ["Şəkər", "Bal", "Limon"],
      },
    },
    {
      id: 14,
      name: "Qəhvə",
      description: "Türk qəhvəsi",
      detailedDescription:
        "Ənənəvi üsulla hazırlanmış Türk qəhvəsi. Xüsusi qəhvə dənələrindən təzə üyüdülərək hazırlanır.",
      ingredients: ["Qəhvə dənəsi", "Su", "Şəkər"],
      price: 4.5,
      image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=300&fit=crop&auto=format",
      options: {
        size: ["Kiçik", "Orta", "Böyük"],
        extras: ["Şəkər", "Süd", "Köpük"],
      },
    },
    {
      id: 15,
      name: "Cappuccino",
      description: "İtalyan qəhvəsi",
      detailedDescription: "Espresso və buxarlanmış süd qarışığı, üstündə süd köpüyü ilə.",
      ingredients: ["Espresso", "Süd", "Süd köpüyü"],
      price: 6.0,
      image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400&h=300&fit=crop&auto=format",
      options: {
        size: ["Kiçik", "Orta", "Böyük"],
        extras: ["Əlavə Shot", "Vanilya", "Karamel"],
      },
    },
    {
      id: 16,
      name: "Təzə Şirə",
      description: "Portağal şirəsi",
      detailedDescription: "Təzə portağallardan sıxılmış təbii şirə. Heç bir qatqı və konservant əlavə edilmir.",
      ingredients: ["Təzə portağal"],
      price: 5.0,
      image: "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=400&h=300&fit=crop&auto=format",
      options: {
        size: ["Kiçik", "Orta", "Böyük"],
        extras: ["Buz", "Nanə"],
      },
    },
    {
      id: 17,
      name: "Smoothie",
      description: "Qarışıq meyvə smoothie",
      detailedDescription: "Təzə meyvələrdən hazırlanmış sağlam və dadlı smoothie.",
      ingredients: ["Banan", "Çiyələk", "Mango", "Yoqhurt", "Bal"],
      price: 8.0,
      image: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=400&h=300&fit=crop&auto=format",
      options: {
        extras: ["Protein tozu", "Chia toxumu", "Əlavə meyvə"],
      },
    },
  ],
  alcohol: [
    {
      id: 18,
      name: "Şərab",
      description: "Qırmızı şərab",
      detailedDescription: "Seçilmiş üzüm növlərindən hazırlanmış keyfiyyətli qırmızı şərab.",
      ingredients: ["Qırmızı üzüm", "Sulfitlər"],
      price: 15.0,
      image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=300&fit=crop&auto=format",
    },
    {
      id: 19,
      name: "Ağ Şərab",
      description: "Soyuq ağ şərab",
      detailedDescription: "Seçilmiş ağ üzüm növlərindən hazırlanmış təzə və meyvəli şərab.",
      ingredients: ["Ağ üzüm", "Sulfitlər"],
      price: 14.0,
      image: "https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=400&h=300&fit=crop&auto=format",
    },
    {
      id: 20,
      name: "Pivə",
      description: "Soyuq pivə",
      detailedDescription: "Təzə dəmlənmiş pivə, soyuq şəkildə təqdim olunur.",
      ingredients: ["Arpa", "Şerbetçiotu", "Maya", "Su"],
      price: 6.0,
      image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?w=400&h=300&fit=crop&auto=format",
      options: {
        size: ["Kiçik", "Orta", "Böyük"],
      },
    },
    {
      id: 21,
      name: "Viski",
      description: "Premium viski",
      detailedDescription: "Uzun müddət yetişdirilmiş premium keyfiyyətli viski.",
      ingredients: ["Arpa", "Su", "Maya"],
      price: 25.0,
      image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=400&h=300&fit=crop&auto=format",
    },
    {
      id: 22,
      name: "Mojito",
      description: "Klassik kokteyl",
      detailedDescription: "Təzə nanə, limon və rom ilə hazırlanmış sərinləşdirici kokteyl.",
      ingredients: ["Ağ rom", "Nanə", "Limon", "Şəkər", "Soda"],
      price: 12.0,
      image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=400&h=300&fit=crop&auto=format",
    },
  ],
}
